service: omni-dw-add-document

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  tags: ${self:custom.tags}
  stackTags: ${self:custom.tags}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DeleteNetworkInterface"
        - "ec2:AssignPrivateIpAddresses"
        - "ec2:UnassignPrivateIpAddresses"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "sqs:GetQueueUrl"
        - "sqs:GetQueueAttributes"
        - "sqs:ReceiveMessage"
        - "sqs:DeleteMessage"
      Resource: "*"
  runtime: nodejs14.x
  environment:
    REGION: ${self:custom.region}
    STAGE: ${self:custom.stage}
  deploymentBucket:
    name: ${ssm:/omni-dw/${self:provider.stage}/sls/deployment/bucket}
    serverSideEncryption: AES256

custom:
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  tags:
    Application: OmniRealTimeReplication
    CreateBy: BizCloudExperts
    Environment: ${self:custom.stage}
  standardResponseHeaders:
    "Access-Control-Allow-Origin": "'*'"
    "Access-Control-Allow-Credentials": "'true'"
    "Access-Control-Allow-Headers": "'*'"

plugins:
  - serverless-offline
  - serverless-provisioned-concurrency-autoscaling

package:
  individually: true

layers:
  OmniAddDocumentLayer:
    path: lambdaLayer/lib
    name: ${self:service}-layer-${self:provider.stage}
    description: Omni add document lambda layer for all node modules - ${self:provider.stage}
    compatibleRuntimes:
      - nodejs14.x
    retain: false


functions:
  customer-response: ${file(config/functions/customer-response.yml):function}
  customer-authorization: ${file(config/functions/customer-authorization.yml):function}
  # create-document: ${file(config/functions/create-document.yml):function}
  # publish-to-wt: ${file(config/functions/publish-to-wt.yml):function}




resources:
  Resources:
    BadRequestResponse:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: ACCESS_DENIED
        ResponseTemplates:
          application/json: |
            {
              "errorDescription":"$context.authorizer.message"
            }
        RestApiId:
          Ref: "ApiGatewayRestApi"
        StatusCode: "400"
    AuthFailureGatewayResponse:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: "ApiGatewayRestApi"
        StatusCode: "401"