---
function:
  handler: src/customer_response.handler
  name: customer-response-add-document-${self:provider.stage}
  description: ${self:service} customer-response - ${self:provider.stage}
  runtime: nodejs14.x
  layers:
    - { Ref: OmniAddDocumentLayerLambdaLayer }
  package:
    include:
      - src/customer_response.js
    exclude:
      - "**/*"  
  events:
    - http:
        path: /shipment/addDocument
        method: POST
        integration: lambda
        private: true
        authorizer:
          name: customer-authorization-add-document
          resultTtlInSeconds: 0
          identitySource: method.request.header.x-api-key
          type: request
        cors: true
        response:
          headers: ${self:custom.standardResponseHeaders}
          statusCodes:
            200:
              pattern: ""
            400:
              pattern: '[\s\S]*\[400\][\s\S]*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
            500:
              pattern: '[\s\S]*\[500\][\s\S]*'
              headers:
                Content-Type: "'application/json'"
              template: ${file(responseTemplate.vtl)}
  environment:
    CUSTOMER_ENTITLEMENT_TABLE: ${ssm:/omni-dw/${self:provider.stage}/customerEntitlement/table}
    SHIPMENT_HEADER_TABLE : ${ssm:/omni-dw/${self:provider.stage}/shipment-header/ddb.tableName}
    SHIPMENT_HEADER_TABLE_INDEX : ${ssm:/omni-dw/${self:provider.stage}/shipment-header-index/ddb.tableIndex}
    ADDRESS_MAPPING_TABLE : ${ssm:/omni-dw/${self:provider.stage}/addressMapping/table}
    UPLOAD_DOCUMENT_API: ${ssm:/omni-dw/${self:provider.stage}/api/addDocument}
    IVIA_CUSTOMERID: ${ssm:/omni-dw/${self:provider.stage}/ivia_customerid}