---
function:
  handler: src/customer-response.handler
  name: customer-response-${self:provider.stage}
  description: ${self:service} customer-response - ${self:provider.stage}
  runtime: nodejs14.x
  layers:
    - { Ref: OmniAddDocumentLayerLambdaLayer }
  package:
    include:
      - src/customer-response.js
    exclude:
      - "**/*"  
  events:
    - http:
        path: /customer-response
        method: POST
        integration: lambda
        private: true
        authorizer:
          name: customer-authorization
          resultTtlInSeconds: 0
          identitySource: method.request.header.x-api-key
          type: request
        cors: true
  environment:
    CUSTOMER_ENTITLEMENT_TABLE: ${ssm:/omni-dw/${self:provider.stage}/customerEntitlement/table}
    SHIPMENT_HEADER_TABLE : ${ssm:/omni-dw/${self:provider.stage}/shipment-header/ddb.tableName}
    SHIPMENT_HEADER_TABLE_INDEX : ${ssm:/omni-dw/${self:provider.stage}/shipment-header-index/ddb.tableIndex}
    ADDRESS_MAPPING_TABLE : ${ssm:/omni-dw/${self:provider.stage}/addressMapping/table}
    UPLOAD_DOCUMENT_API: ${ssm:/omni-dw/${self:provider.stage}/api/addDocument}