---
function:
  handler: src/customer-response.handler
  name: customer-response-${self:provider.stage}
  description: ${self:service} customer-response - ${self:provider.stage}
  runtime: nodejs14.x
  package:
    include:
      - src/customer-response.js
    exclude:
      - "**/*"  
  events:
    - http:
        path: /customer-response
        method: POST
        integration: lambda
        private: true
        authorizer:
          name: customer-authorization
          resultTtlInSeconds: 0
          identitySource: method.request.header.x-api-key
          type: request
        cors: true
        # response:
        #   headers: ${self:custom.standardResponseHeaders}
        #   statusCodes:
        #     200:
        #       pattern: ""
        #     400:
        #       pattern: '[\s\S]*\[400\][\s\S]*'
        #       headers:
        #         Content-Type: "'application/json'"
        #       template: ${file(responseTemplate.vtl)}
        #     500:
        #       pattern: '[\s\S]*\[500\][\s\S]*'
        #       headers:
        #         Content-Type: "'application/json'"
        #       template: ${file(responseTemplate.vtl)}
